### PR TITLE
update

### PR DESCRIPTION
**Pull request by barmaglot92**

### CODE REVIEW

**Comment by floatdrop** [comment]
Please stop, I'm on it already :dog:

**Comment by barmaglot92** [comment]
nice, thanks )

On Wed, Jan 21, 2015 at 5:31 PM, Vsevolod Strukchinsky <
notifications@github.com> wrote:

> Please stop, I'm on it already [image: :dog:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/floatdrop/express-mongo-db/pull/4#issuecomment-70846413
> .

## 

С уважением,

Жвакин Андрей

Программист

проекта Связной Трэвел

Моб. +7 (985) 257-57-34

Телефон: +7 (495) 287-03-33  доб.401781

**Comment by barmaglot92** [comment]
when it has been updated in npm ?

**Comment by floatdrop** [comment]
Just now. Use `npm i express-mongo-db@1.0.0`.

**Comment by barmaglot92** [comment]
express-mongo-db :)

**Comment by floatdrop** [comment]
Yep :)

**Pull request closed without merging**
