### PR TITLE
update index.js

### PR DESCRIPTION
**Pull request by barmaglot92**
Please add following changes to authorization on mongodb if needed.

### CODE REVIEW

**Comment by floatdrop** [comment]
Use [mongodb-uri](https://www.npmjs.com/package/mongodb-uri) to build valid connection string.

**Comment by barmaglot92** [comment]
But i can`t set connectionString using your module.
'mongodb://' + options.host + '/' + options.db,

or it is possible use options.options? but i don`t find solution.

**Comment by floatdrop** [comment]
@barmaglot92 I'm suggesting use mongodb-uri in this PR to build valid cs. Otherwise this breaks test on connection without password.

**Comment by barmaglot92** [comment]
Okay i understand.
Create new PR for you?

**Comment by floatdrop** [comment]
You can change this pr or create new.

**Comment by barmaglot92** [comment]
I updated package.json, in another PR.
Index.js has been updated too.

**Comment by barmaglot92** [comment]
Probably readme needed to update

**Comment by barmaglot92** [comment]
mongodb-uri module not found.. i try add it to package but not effect

**Pull request closed without merging**
